// src/config/endpointConfig.ts

export const endpointConfig = {
    '/publications/Updateorsave': {
      formFields: [
        'id', 'facultyid', 'year', 'branchid', 'sem', 'subjectcode',
        'section', 'assessmenttools', 'acadamicid', 'verifiedstatus',
      ],
      fieldTypes: {
        id: 'number',
        facultyid: 'string',
        year: 'number',
        branchid: 'number',
        sem: 'number',
        subjectcode: 'string',
        section: 'string',
        assessmenttools: 'string',
        acadamicid: 'number',
        verifiedstatus: 'string',
      },
    },
    '/publications/PublicationsGainingITUpdateorsave': {
      formFields: [
        'id', 'typeofcertificationprogram', 'certificationprogramtitle', 'certificationprogramduration',
        'uploadcertificate', 'certificationprogram', 'certificationprogramamount', 'facultyid',
        'certificationdate', 'certificationtype', 'verificationby', 'verifiedstatus',
      ],
      fieldTypes: {
        id: 'number',
        typeofcertificationprogram: 'string',
        certificationprogramtitle: 'string',
        certificationprogramduration: 'string',
        uploadcertificate: 'string',
        certificationprogram: 'string',
        certificationprogramamount: 'number',
        facultyid: 'string',
        certificationdate: 'date',
        certificationtype: 'string',
        verificationby: 'string',
        verifiedstatus: 'string',
      },
    },
    '/publications/publicationproductUpdateorsave': {
      formFields: [
        'id', 'title', 'producttype', 'date', 'datetime', 'members',
        'condetedby', 'proof', 'verifiedstatus', 'facultyid',
      ],
      fieldTypes: {
        id: 'number',
        title: 'string',
        producttype: 'string',
        date: 'date',
        datetime: 'date',
        members: 'string',
        condetedby: 'string',
        proof: 'string',
        verifiedstatus: 'string',
        facultyid: 'string',
      },
    },
    '/publications/PublicationsCourtUpdateorsave': {
      formFields: [
        'id', 'title', 'court', 'decideddate', 'reporter1', 'reporter2',
        'reporter3', 'docketid', 'facultyid', 'verificationby', 'verifiedstatus',
      ],
      fieldTypes: {
        id: 'number',
        title: 'string',
        court: 'string',
        decideddate: 'date',
        reporter1: 'string',
        reporter2: 'string',
        reporter3: 'string',
        docketid: 'string',
        facultyid: 'string',
        verificationby: 'string',
        verifiedstatus: 'string',
      },
    },
    '/publications/PublicationsContentUpdateorsave': {
      formFields: [
        'id', 'contenttitle', 'type', 'datetime', 'acadamicid', 'facultyid',
        'verifiedby', 'verifiedstatus', 'verifieddatetime',
      ],
      fieldTypes: {
        id: 'number',
        contenttitle: 'string',
        type: 'string',
        datetime: 'date',
        acadamicid: 'number',
        facultyid: 'string',
        verifiedby: 'string',
        verifiedstatus: 'string',
        verifieddatetime: 'date',
      },
    },
    '/publications/PublicationsConferenceUpdateorsave': {
      formFields: [
        'id', 'title', 'authors', 'publicationdate', 'conference', 'volume',
        'issue', 'pages', 'facultyid', 'conferencetype', 'issnnumber',
        'doinumber', 'categorytype', 'verificationby', 'verifiedstatus',
        'scopusurl', 'uploadfileurl',
      ],
      fieldTypes: {
        id: 'number',
        title: 'string',
        authors: 'string',
        publicationdate: 'date',
        conference: 'string',
        volume: 'string',
        issue: 'string',
        pages: 'string',
        facultyid: 'string',
        conferencetype: 'string',
        issnnumber: 'string',
        doinumber: 'string',
        categorytype: 'string',
        verificationby: 'string',
        verifiedstatus: 'string',
        scopusurl: 'string',
        uploadfileurl: 'string',
      },
    },
    '/publications/PublicationsChapterUpdateorsave': {
      formFields: [
        'id', 'title', 'authors', 'publicationdate', 'book', 'volume',
        'issue', 'pages', 'publisher', 'facultyid', 'verificationby',
        'verifiedstatus', 'link', 'authornumber',
      ],
      fieldTypes: {
        id: 'number',
        title: 'string',
        authors: 'string',
        publicationdate: 'date',
        book: 'string',
        volume: 'string',
        issue: 'string',
        pages: 'string',
        publisher: 'string',
        facultyid: 'string',
        verificationby: 'string',
        verifiedstatus: 'string',
        link: 'string',
        authornumber: 'number',
      },
    },
    '/publications/PublicationsCertificationUpdateorsave': {
      formFields: [
        'id', 'typeofcertificationprogram', 'certificationprogramtitle', 'certificationprogramduration',
        'uploadcertificate', 'certificationprogram', 'certificationprogramamount', 'facultyid',
        'certificationdate', 'certificationtype', 'certificationstatus', 'expecteddate',
        'verificationby', 'verifiedstatus', 'uploadfileurl',
      ],
      fieldTypes: {
        id: 'number',
        typeofcertificationprogram: 'string',
        certificationprogramtitle: 'string',
        certificationprogramduration: 'string',
        uploadcertificate: 'string',
        certificationprogram: 'string',
        certificationprogramamount: 'number',
        facultyid: 'string',
        certificationdate: 'date',
        certificationtype: 'string',
        certificationstatus: 'string',
        expecteddate: 'date',
        verificationby: 'string',
        verifiedstatus: 'string',
        uploadfileurl: 'string',
      },
    },
  };
  